name: Release Notes

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version
        id: ver
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Generate notes from CHANGELOG
        id: notes
        run: |
          VERSION=${GITHUB_REF##*/}
          awk -v ver="${VERSION#v}" '/^## \['ver'\]/ {flag=1;next} /^## \[/ {if(flag) exit} flag {print}' CHANGELOG.md > relnotes.txt
          echo 'notes<<EOF' >> $GITHUB_OUTPUT
          cat relnotes.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
